### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by guest73** [fidli/NB-SplitScreen#1]
I've got the following exception

java.lang.ClassCastException: qubexplorer.ui.SonarIssuesTopComponent cannot be cast to org.openide.windows.CloneableTopComponent
	at eu.fidli.tabgroupswitch.AttachFileToNextTabGroup.actionPerformed(AttachFileToNextTabGroup.java:41)
	at org.openide.awt.AlwaysEnabledAction$1.run(AlwaysEnabledAction.java:199)
	at org.openide.util.actions.ActionInvoker$1.run(ActionInvoker.java:95)
	at org.openide.util.actions.ActionInvoker.doPerformAction(ActionInvoker.java:116)
	at org.openide.util.actions.ActionInvoker.invokeAction(ActionInvoker.java:99)
	at org.openide.awt.AlwaysEnabledAction.actionPerformed(AlwaysEnabledAction.java:202)
	at org.openide.windows.TopComponent.processKeyBinding(TopComponent.java:1176)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2963)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2863)
	at java.desktop/java.awt.Component.processEvent(Component.java:6355)
	at java.desktop/java.awt.Container.processEvent(Container.java:2259)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4961)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2317)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4793)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1955)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:827)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1096)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:966)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:792)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4842)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2317)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2758)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4793)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:99)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by fidli** [comment]
I would need more information, like is this a compilation error, or runtime?

What are your versions of netbeans/java?

**Comment by guest73** [comment]
Oh, yes, sorry.

Product Version: NetBeans IDE Dev (Build 201803280002)
Java: 9.0.4; Java HotSpot(TM) 64-Bit Server VM 9.0.4+11
Runtime: Java(TM) SE Runtime Environment 9.0.4+11
System: Linux version 4.9.0-6-amd64 running on amd64; UTF-8; en_US (nb)

This is a runtime error.

Ok. I think the problem is I was trying to use this plugin in a wrong way :) Just tried with Projects tab and it gave me a similar exception. I have F12 bound to "Dock current file to next tab group" and when I press it on a "normal" Editor tab it works, but when I press it on Projects or Files tab it gives an exception.
Why I came to such a situation :) is, I accidentally dragged a tab(Which is a tab similar to Projects or Files) of radar-netbean plugin into an Editor Document Group making it kind of a regular Editor Tab and then I thought pressing F12 might work on it :). In any case it is not common situation to keep tabs like Projects, Favorites, Navigator in the Editor's Document Group. But you still may want to add a check in the code to verify the Tab is of a proper type and can be moved with key combination.

**Comment by guest73** [comment]
![2018-04-02-123725_1915x987_scrot](https://user-images.githubusercontent.com/4907799/38192005-8c48b546-3673-11e8-9f37-6ecb029c3824.png)

**Comment by fidli** [comment]
I will look into this, but I dont know how fast.

How much does this bug you?

**Comment by guest73** [comment]
Not at all :) I'm just not gonna press F12 on those kind of tabs. Take your time. And thanks for the support.
